// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "dbba97b3-6500-45f0-998f-11b667805f4b";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onCurrentMessageChange();
void onPreviousMessageChange();
void onRelayChange();
void onStatusChange();

String currentMessage;
String previousMessage;
CloudSchedule timer;
bool relay;
bool status;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(currentMessage, READWRITE, ON_CHANGE, onCurrentMessageChange);
  ArduinoCloud.addProperty(previousMessage, READWRITE, ON_CHANGE, onPreviousMessageChange);
  ArduinoCloud.addProperty(timer, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(relay, READWRITE, ON_CHANGE, onRelayChange);
  ArduinoCloud.addProperty(status, READWRITE, ON_CHANGE, onStatusChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
